# Generated by Django 4.2.3 on 2026-05-05 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_alter_company_user'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Prérequis et exigences pour les candidats')),
                ('location', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('FREELANCE', 'Freelance'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance')], max_length=20)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('submission_deadline', models.DateTimeField(help_text='Date limite de soumission des candidatures')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, help_text='Durée du contrat/mission', max_length=100)),
                ('criteria', models.JSONField(default=dict, help_text="Critères d'évaluation des candidats")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert'), ('closed', 'Fermé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='rfp_attachments/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfps', to='companies.company')),
            ],
            options={
                'verbose_name': "Appel d'offre",
                'verbose_name_plural': "Appels d'offres",
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('proposed_amount', models.DecimalField(decimal_places=2, help_text='Montant proposé', max_digits=10)),
                ('proposed_timeline', models.CharField(help_text='Délai proposé pour réaliser la mission', max_length=200)),
                ('proposal_document', models.FileField(blank=True, null=True, upload_to='proposals/')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examinée'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('shortlisted', 'Présélectionnée')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Notes internes de l'entreprise")),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='jobs.requestforproposal')),
            ],
            options={
                'ordering': ['-submitted_date'],
                'unique_together': {('rfp', 'candidate')},
            },
        ),
    ]
