# Generated by Django 4.2.3 on 2026-05-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_requestforproposal_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='job_description_file',
            field=models.FileField(blank=True, help_text='PDF contenant la description détaillée du poste', null=True, upload_to='job_descriptions/'),
        ),
    ]
